"""Fixing the missing metadata syndrome with .toml files"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/30_annotating-your-shared-data-with-TOML.ipynb.

# %% auto #0
__all__ = ['ReadTOML', 'data_now']

# %% ../notebooks/30_annotating-your-shared-data-with-TOML.ipynb #ff93b9ec-f772-46d7-8f7f-87a9c95fc779
from . import DataViewer, login, filters 
import toml

# %% ../notebooks/30_annotating-your-shared-data-with-TOML.ipynb #9c391604-e0de-4d4c-a255-645d69feb4b7
class ReadTOML(): 

    def __init__(self, url, toml_search, use_regex=False, nc_key='nc', verbose=False): 
        '''From nextcloud folder at `url` download and parse toml file matching `toml_search` string.'''
        
        # download the toml file 
        dv = DataViewer(login(url, verbose=False), **filters(search=toml_search, use_regex=use_regex, extensions=['.toml']))
        files = dv.download_filtered(verbose=False) 
    
        # check if we find only one unique matching toml file  
        n_files = len(files)
        #assert (n_files == 1), f'Found {n_files} .toml files in nextcloud folder {url} matching {search}: \n {files}' 
        assert n_files == 1, f'Found {n_files} .toml files in nextcloud folder {url} matching "{toml_search}": \n {files}' 

        # read and parse toml file 
        self.toml_file = files[0]
        self.toml_dict = toml.load(self.toml_file)  
        
        with open(self.toml_file, 'r') as fh: 
            self.toml_txt = fh.read()
        if verbose:
            print(f'Here is the content of {toml_file}: \n')  
            print(self.toml_txt)

        # create dictionary for to nextcloud [nc] regular expression file patterns   
        if nc_key is not None: 
            self.toml_nc_dict = self.toml_dict[nc_key] 
        else: 
            self.toml_nc_dict = self.toml_dict 

            
def data_now(url, toml_txt, nc_key='nc', verbose=True): 
    '''Download complete dataset as described in your toml file matching `toml_txt` string with `nc_key` to your local computer.'''
    
    # parse toml text string 
    
    toml_dict = toml.loads(toml_txt) 
    toml_nc_dict = toml_dict[nc_key] 

    # instantiate dataviewer now with use_regex=True
    dv = DataViewer(login(url, verbose=verbose), **filters(search='', use_regex=True, extensions=[]))

    # iterate over keys and search for regular expression file patterns 
    key_list = list(toml_nc_dict.keys()) 
    n_keys = len(key_list)  

    files_dict = {}

    if verbose: 
        print(f'\nSyncing files to cache for the following {n_keys} file groups:') 
        
    for i, k in enumerate(key_list): 
        if verbose: 
            print(f"[{i}] '{k}'                  ") 
        
        # update param search string 
        dv.search = toml_nc_dict[k] 

        # download files to fairdatanow cache and return local file paths 
        files = dv.download_filtered(verbose=verbose) 

        # add file paths to dictionary 
        files_dict[k] = files 

    print('Ready!')

    return files_dict 
           
    
