"""Fixing the missing metadata syndrome with .toml files"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/30_annotating-your-shared-data-with-TOML.ipynb.

# %% auto #0
__all__ = ['data_now']

# %% ../notebooks/30_annotating-your-shared-data-with-TOML.ipynb #ff93b9ec-f772-46d7-8f7f-87a9c95fc779
from . import DataViewer, login, filters 
import tomlkit

# %% ../notebooks/30_annotating-your-shared-data-with-TOML.ipynb #9c391604-e0de-4d4c-a255-645d69feb4b7
def data_now(url, toml_txt, verbose=False): 
    '''Download all the data present in the data table in your TOML file.'''
    
    #with open(toml_file, "r") as toml_file:
    doc = tomlkit.loads(toml_txt)

    data_table = doc['data']
    tablelist = list(data_table.keys())

    dv = DataViewer(login(url, verbose=verbose), **filters(search='', use_regex=True, extensions=[]))
    files_dict = {}

    for table in tablelist: 
        files_dict[table] = {}
        if verbose: 
            print(f'\nSyncing files to cache for the following {n_keys} file groups:')
        for k in data_table[table]:
            dv.search = data_table[table][k] 
            # download files to fairdatanow cache and return local file paths 
            files = dv.download_filtered(verbose=verbose)
            files_dict[table][k] = files
        print(f"Found {len(files_dict[table])} files in table: ['{table}'].")
    print("Ready!")
    return files_dict
           
    
