# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/12_dataviewer.ipynb.

# %% auto 0
__all__ = ['DataViewer']

# %% ../notebooks/12_dataviewer.ipynb 7
import panel as pn
import param
from panel.viewable import Viewer
import pandas as pd
from humanize import naturalsize

pn.extension("tabulator")

# %% ../notebooks/12_dataviewer.ipynb 8
class DataViewer(Viewer):
    data = param.DataFrame()

    columns = param.ListSelector(default=["path", "size", "modified"])

    search = param.String(default="xray")

    bytes_amount = param.Integer()
    
    filtered_data = param.DataFrame()

    def __init__(self, **params):
        super().__init__(**params)
        # load all options for the ListSelectors
        self.param.columns.objects = self.data.columns.to_list()

    @param.depends("data", "columns", "search", watch=True, on_init=True)
    def _update_filtered_data(self):
        # set the base df for readability and a non-watched variable
        df = self.data
        # search the dataframe in column path if it contains the search string
        searched_df = df[df["path"].str.contains(self.search)]
        # save the total bytes_size in the bytes_amount variable
        self.bytes_amount = searched_df['byte_size'].sum()
        # only select the columns from the column selector
        self.filtered_data = searched_df[self.columns]
    
    @param.depends("filtered_data")
    def number_of_rows(self):
        return f"Rows: {len(self.filtered_data)} Filesize: {naturalsize(self.bytes_amount, True)}"
    
    def __panel__(self):
        return pn.Column(
            pn.Row(pn.widgets.TextInput.from_param(self.param.search), pn.widgets.MultiChoice.from_param(self.param.columns)),
            pn.widgets.Tabulator(self.param.filtered_data, height=350, pagination=None, show_index=False, selectable=True, disabled=True),
            self.number_of_rows
        )
